<form
    action="<?=APP::config('url') ?>gledanje/novo" 
    method="POST">


        <div class="large-6 small-12 cell">
            <label>Film
              <select name="film" id="film">
                <option <?php if($entitet->film==0){
                    echo ' selected="selected" ';
                }?> value="0">Odaberite film</option>
                <?php foreach($filmovi as $film): ?>
                    <option <?php if($entitet->film==$film->sifra){
                    echo ' selected="selected" ';
                }?> value="<?=$film->sifra?>"><?=$film->naziv?></option>
                <?php endforeach; ?>
              </select>
            </label>
        </div>
        
       

        <div class="large-12 small-12 cell">
        <label>Korisnik
              <select name="korisnik" id="korisnik">
                <option <?php if($entitet->korisnik==0){
                    echo ' selected="selected" ';
                }?> value="0">Odaberite korisnika</option>
                <?php foreach($korisnici as $korisnik): ?>
                    <option <?php if($entitet->korisnik==$korisnik->sifra){
                    echo ' selected="selected" ';
                }?> value="<?=$korisnik->sifra?>"><?=$korisnik->korisnicko_ime?></option>
                <?php endforeach; ?>
              </select>
            </label>
        </div>
        
        
        
        <div class="large-12 small-12 cell">
            <label>Vrijeme gledanja
                <input type="date" name="vrijeme_gledanja" 
                value="<?=$entitet->vrijeme_gledanja?>" />
            </label>
        </div>
    </div>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>gledanje/index">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Unesi novo gledanje"></input>
        </div>
    </div>

</form>