<a class="button expanded secondary" 
href="<?=APP::config('url') ?>dobavljac/novo">
    <?php include BP . 'view/predlozak/izgledDodajNovi.phtml' ?>
</a>
<table class="table">
    <thead>
        <tr>
            <th>Naziv</th>
            <th>Homepage</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $entitet): ?>
            <tr>
                <td><?=$entitet->naziv?></td>
                <td><?=$entitet->homepage?></td>
                <td>
                <a href="<?=APP::config('url') ?>dobavljac/promjena?sifra=<?=$entitet->sifra?>&stranica=<?=$trenutna?>">
                <?php include BP . 'view/predlozak/izgledPromjeni.phtml' ?>
                </a>
                
                <a onclick="return confirm('Sigurno obrisati?');"
                href="<?=APP::config('url') ?>dobavljac/brisanje?sifra=<?=$entitet->sifra?>">
                        <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                    </a>
                    
                    </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="?stranica=<?=$prethodna?>&uvjet=<?=$uvjet?>" aria-label="Previuos page">Prethodno</a></li>
    <li class="current"><span class="show-for-sr">Vi ste na</span> <?=$trenutna?> / <?=$ukupnoStranica?></li>
    <li class="pagination-next"><a href="?stranica=<?=$sljedeca?>&uvjet=<?=$uvjet?>" aria-label="Next page">Sljedeće</a></li>
  </ul>
</nav>