<form
    action="<?=APP::config('url') ?>dobavljac/novo" 
    method="POST">

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Naziv
                <input type="text" name="naziv" 
                value="<?=$entitet->naziv?>" />
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Homepage
                <input type="text" name="homepage" 
                value="<?=$entitet->homepage?>" />
            </label>
        </div>

       </div> 

    

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>dobavljac/index">
            Odustani
        </a>    
        
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Unesi novog dobavljaca"></input>
        </div>
        
    </div>

</form>