<form
    action="<?=APP::config('url') ?>dobavljac/promjena" 
    method="POST">

    <label>Naziv
        <input type="text" name="naziv" 
        value="<?=$entitet->naziv?>" />
    </label>

    <label>Homepage
        <input type="text" name="homepage" 
        value="<?=$entitet->homepage?>" />
    </label>

    <input type="hidden" name="sifra" value="<?=$dobavljac->sifra ?>" />

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>dobavljac/index?stranica=<?=$trenutna?>">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Promjeni dobavljača"></input>
        </div>
    </div>

</form>