<nav class="top-bar topbar-responsive">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
    <li>
    <a href="<?=APP::config('url') ?>">
            <?=APP::config('nazivAPP') ?>
        </a>
    </li>

      <li><a href="<?=APP::config('url') ?>index/onama">O nama</a></li>

      <?php if(isset($_SESSION['autoriziran'])): ?>
        <!-- ovdje dođe privatni dio izbornika -->
        <li>
        
          <a href="<?=APP::config('url') ?>nadzornaploca/index">Nadzorna ploča</a>
          <li><a href="<?=APP::config('url') ?>korisnik/index">Korisnici</a></li>
          <li><a href="<?=APP::config('url') ?>film/index">Filmovi</a></li>
          <li><a href="<?=APP::config('url') ?>zanr/index">Žanrovi</a></li>
          <li><a href="<?=APP::config('url') ?>dobavljac/index">Dobavljači</a></li>
          <?php if($_SESSION['autoriziran']->uloga==='admin'): ?>
            <li><a href="<?=APP::config('url') ?>operater/index">Operateri</a></li>
          <?php endif; ?>
        </ul>
      </li>

      <?php endif; ?>
        </ul>
      </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
    <li>
          <?php if(!isset($_SESSION['autoriziran'])): ?>
            <a href="<?=APP::config('url') ?>index/login">Login</a>
          <?php else: ?>
            <a href="<?=APP::config('url') ?>index/logout">Logout</a>
          <?php endif; ?>

        </li>
    </ul>
  </div>
</div> 