<a class="button expanded secondary" 
href="<?=APP::config('url') ?>zanr/novo">
    <?php include BP . 'view/predlozak/izgledDodajNovi.phtml' ?>
</a>
<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="?stranica=<?=$prethodna?>&uvjet=<?=$uvjet?>" aria-label="Previuos page">Prethodno</a></li>
    <li class="current"><span class="show-for-sr">Vi ste na</span> <?=$trenutna?> / <?=$ukupnoStranica?></li>
    <li class="pagination-next"><a href="?stranica=<?=$sljedeca?>&uvjet=<?=$uvjet?>" aria-label="Next page">Sljedeće</a></li>
  </ul>
</nav>

<?php 
foreach($entiteti as $entitet):
?>

<div class="callout callout-hover-reveal" data-callout-hover-reveal>
  <div class="callout-body">

    <h2><?=$entitet->naziv; ?>
                <a href="<?=APP::config('url') ?>zanr/promjena?sifra=<?=$entitet->sifra?>&stranica=<?=$trenutna?>">
                <?php include BP . 'view/predlozak/izgledPromjeni.phtml' ?>
                </a>
                
                    <a onclick="return confirm('Sigurno obrisati?');"
                    href="<?=APP::config('url') ?>zanr/brisanje?sifra=<?=$entitet->sifra?>">
                        <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
                    </a>
                
                    </h2>
  </div>
  <div class="callout-footer">
  <p><?=$entitet->opis; ?></p>
  </div>
</div>

<?php 
endforeach;
?>

<nav aria-label="Pagination">
  <ul class="pagination text-center">
    <li class="pagination-previous"><a href="?stranica=<?=$prethodna?>&uvjet=<?=$uvjet?>" aria-label="Previuos page">Prethodno</a></li>
    <li class="current"><span class="show-for-sr">Vi ste na</span> <?=$trenutna?> / <?=$ukupnoStranica?></li>
    <li class="pagination-next"><a href="?stranica=<?=$sljedeca?>&uvjet=<?=$uvjet?>" aria-label="Next page">Sljedeće</a></li>
  </ul>
</nav>