<form
    action="<?=APP::config('url') ?>zanr/novo" 
    method="POST">

    <label>Naziv
        <input type="text" name="naziv" 
        value="<?=$entitet->naziv?>" />
    </label>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Opis
                <textarea name="opis" cols="30" 
                rows="5"><?=$entitet->opis?></textarea>
            </label>
        </div>
        </div>

    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>zanr/index">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Unesi novi žanr"></input>
        </div>
    </div>

</form>