<form
    action="<?=APP::config('url') ?>korisnik/promjena" 
    method="POST">

    

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
            <label>Ime
                <input type="text" name="ime" 
                value="<?=$entitet->ime?>" />
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Prezime
                <input type="text" name="prezime" 
                value="<?=$entitet->prezime?>" />
            </label>
        </div>

        <div class="large-6 small-12 cell">
            <label>Korisničko ime
                <input type="text" name="korisnicko_ime" 
                value="<?=$entitet->korisnicko_ime?>" />
            </label>
        </div>
        <div class="large-6 small-12 cell">
            <label>Adresa
                <input type="text" name="adresa" 
                value="<?=$entitet->adresa?>" />
            </label>
        </div>

        <div class="large-12 small-12 cell">
            <label>Email
                <input type="text" name="email" 
                value="<?=$entitet->email?>" />
            </label>
        </div>
        <div class="large-12 small-12 cell">
            <label>Broj mobitela
                <input type="text" name="broj_mobitela" 
                value="<?=$entitet->broj_mobitela?>" />
            </label>
        </div>
        <div class="large-12 small-12 cell">
            <label>Datum rođenja
                <input type="date" name="datum_rodenja" 
                value="<?=$entitet->datum_rodenja?>" />
            </label>
        </div>
    </div>

    <input type="hidden" name="sifra" value="<?=$entitet->sifra ?>" />


    <p>
        <?=$poruka ?>
    </p>

    <div class="grid-x grid-padding-x">
        <div class="large-6 small-12 cell">
        <a class="button expanded alert" 
        href="<?=APP::config('url') ?>korisnik/index?stranica=<?=$trenutna?>">
            Odustani
        </a>    
        </div>
        <div class="large-6 small-12 cell">
            <input type="submit" class="button expanded" 
                value="Promjeni korisnika"></input>
        </div>
    </div>

</form>