<form>
  <div class="sign-in-form">
    
    <h4 class="text-center">Prijava</h4>
    <form class="log-in-form" 
     action="<?=APP::config('url') ?>index/autorizacija" 
     method="POST">
    
    <label for="sign-in-form-username">Email
    <input type="email" name="email" placeholder="ivan@primjer.hr" 
        value="<?=$email ?>">
    </label>
    
    <label for="sign-in-form-password">Lozinka
    <input type="password" name="lozinka" placeholder="Lozinka">
    
    <button type="submit" class="sign-in-form-button">Prijavi se</button>
    <?=$poruka ?>
  </div>
</form>




